-- $Id$

CREATE TABLE INTERNAL_TOKENS(
    TOKEN CHAR(64) NOT NULL,
    UDID CHAR(40) NOT NULL,
    LOGINNAME VARCHAR2(20) NOT NULL,
    ROLECODE VARCHAR2(32) NOT NULL,
    UPSAPPLICATIONNAME  VARCHAR2(50) NOT NULL,
    EXPIRATION_DATE DATE NOT NULL,
    CREATION_DATE DATE NOT NULL,
    CONSTRAINT PK_INTERNAL_TOKENS PRIMARY KEY (TOKEN, UDID)
);